services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - acervo_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - acervo_network

#  backend:
#    build: .
#    container_name: python_backend
#    depends_on:
#      mysql:
#        condition: service_healthy
#    ports:
#      - "8000:8000"
#    environment:
#      DATABASE_URL: mysql+pymysql://appuser:apppassword@mysql:3306/testdb?charset=utf8mb4
#    volumes:
#      - .:/app
#    command: python app.py
#    networks:
#      - acervo_network

volumes:
  acervo_mysql_data:

networks:
  acervo_network:
    driver: bridge